# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ardhiraka/FSDS_Guidelines/blob/master/p2/w3/d2am_deploy.ipynb

# Deployment with Streamlit

Streamlit is an open-source Python library that makes it easy to create and share beautiful, custom web apps for machine learning and data science. In just a few minutes you can build and deploy powerful data apps - so let’s get started!

1. Make sure that you have Python 3.6+ installed.
2. Install Streamlit using PIP and run the ‘hello world’ app:

```sh
pip install streamlit
streamlit hello
```

That’s it! In the next few seconds the sample app will open in a new tab in your default browser.

Still with us? Great! Now make your own app in just 3 more steps:

1. Open a new Python file, import Streamlit, and write some code
2. Run the file with: `streamlit run [filename]`
3. When you’re ready, click `Deploy` from the Streamlit menu to share your app with the world!

Now that you’re set up, let’s dive into more of how Streamlit works and how to build great apps.

## Create your first Streamlit app

First, we’ll create a new Python script and import Streamlit.

- Create a new Python file named first_app.py, then open it with your IDE or text editor.
- Next, import Streamlit.

```py
import streamlit as st
# To make things easier later, we're also importing numpy and pandas for
# working with sample data.
import numpy as np
import pandas as pd
```

- Run your app. A new tab will open in your default browser. It’ll be blank for now. That’s OK.

`streamlit run first_app.py`

Running a Streamlit app is no different than any other Python script. Whenever you need to view the app, you can use this command.

- You can kill the app at any time by typing Ctrl+c in the terminal.

## Add text and data

### Add a title

Streamlit has a number of ways to add text to your app. Check out our API reference for a complete list.

Let’s add a title to test things out:

`st.title('My first app')`

That’s it! Your app has a title. You can use specific text functions to add content to your app, or you can use `st.write()` and add your own markdown.

### Write a data frame

Along with magic commands, `st.write()` is Streamlit’s "Swiss Army knife". You can pass almost anything to `st.write()`: text, data, Matplotlib figures, Altair charts, and more. Don’t worry, Streamlit will figure it out and render things the right way.

```py
st.write("Here's our first attempt at using data to create a table:")
st.write(pd.DataFrame({
    'first column': [1, 2, 3, 4],
    'second column': [10, 20, 30, 40]
}))
```

There are other data specific functions like `st.dataframe()` and `st.table()` that you can also use for displaying data. Check our advanced guides on displaying data to understand when to use these features and how to add colors and styling to your data frames.

## Use magic

You can also write to your app without calling any Streamlit methods. Streamlit supports “magic commands,” which means you don’t have to use st.write() at all! Try replacing the code above with this snippet:

```py
'''
# My first app
Here's our first attempt at using data to create a table:
'''

df = pd.DataFrame({
  'first column': [1, 2, 3, 4],
  'second column': [10, 20, 30, 40]
})

df
```

Any time that Streamlit sees a variable or a literal value on its own line, it automatically writes that to your app using st.write(). For more information, refer to the documentation on magic commands.

## Draw charts and maps

Streamlit supports several popular data charting libraries like Matplotlib, Altair, deck.gl, and more. In this section, you’ll add a bar chart, line chart, and a map to your app.

### Draw a line chart

You can easily add a line chart to your app with `st.line_chart()`. We’ll generate a random sample using Numpy and then chart it.

```py
chart_data = pd.DataFrame(
     np.random.randn(20, 3),
     columns=['a', 'b', 'c'])

st.line_chart(chart_data)
```

### Plot a map

With `st.map()` you can display data points on a map. Let’s use Numpy to generate some sample data and plot it on a map of San Francisco.

```py
map_data = pd.DataFrame(
    np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
    columns=['lat', 'lon'])

st.map(map_data)
```

## Add interactivity with widgets

With widgets, Streamlit allows you to bake interactivity directly into your apps with checkboxes, buttons, sliders, and more. Check out our API reference for a full list of interactive widgets.

### Use checkboxes to show/hide data

One use case for checkboxes is to hide or show a specific chart or section in an app. `st.checkbox()` takes a single argument, which is the widget label. In this sample, the checkbox is used to toggle a conditional statement.

```py
if st.checkbox('Show dataframe'):
    chart_data = pd.DataFrame(
       np.random.randn(20, 3),
       columns=['a', 'b', 'c'])

    chart_data
```

### Use a selectbox for options

Use `st.selectbox` to choose from a series. You can write in the options you want, or pass through an array or data frame column.

Let’s use the `df` data frame we created earlier.

```py
option = st.selectbox(
    'Which number do you like best?',
     df['first column'])

'You selected: ', option
```

## Lay out your app

For a cleaner look, you can move your widgets into a sidebar. This keeps your app central, while widgets are pinned to the left. Let’s take a look at how you can use `st.sidebar` in your app.

```py
option = st.sidebar.selectbox(
    'Which number do you like best?',
     df['first column'])

'You selected:', option
```

Most of the elements you can put into your app can also be put into a sidebar using this syntax: `st.sidebar.[element_name]()`. Here are a few examples that show how it’s used: `st.sidebar.markdown()`, `st.sidebar.slider()`, `st.sidebar.line_chart()`.

You can also use `st.columns` to lay out widgets side-by-side, or `st.expander` to conserve space by hiding away large content.

```py
left_column, right_column = st.columns(2)
pressed = left_column.button('Press me?')
if pressed:
  right_column.write("Woohoo!")

expander = st.expander("FAQ")
expander.write("Here you could put in some really, really long explanations...")
```

The only exceptions right now are `st.echo` and `st.spinner`. Rest assured, though, we’re currently working on adding support for those too!

## Show progress

When adding long running computations to an app, you can use `st.progress()` to display status in real time.

First, let’s import time. We’re going to use the `time.sleep()` method to simulate a long running computation:

`import time`

Now, let’s create a progress bar:

```py
'Starting a long computation...'

# Add a placeholder
latest_iteration = st.empty()
bar = st.progress(0)

for i in range(100):
  # Update the progress bar with each iteration.
  latest_iteration.text(f'Iteration {i+1}')
  bar.progress(i + 1)
  time.sleep(0.1)

'...and now we\'re done!'
```

## Share your app

After you’ve built a Streamlit app, it’s time to share it! To show it off to the world you can use Streamlit Cloud to deploy, manage, and share your app. Streamlit Cloud is currently invitation only, so please request an invite and we’ll get you one soon!

It works in 3 simple steps:

- Put your app in a public Github repo (and make sure it has a requirements.txt!)
- Sign into share.streamlit.io
- Click ‘Deploy an app’ and then paste in your GitHub URL

## Interactive Widget

### Button

```py
if st.button('Say hello'):
    st.write('Why hello there')
else:
    st.write('Goodbye')
```

### Download Button

```py
@st.cache
def convert_df(df):
    # IMPORTANT: Cache the conversion to prevent computation on every rerun
    return df.to_csv().encode('utf-8')
csv = convert_df(my_large_df)
st.download_button(
    label="Download data as CSV",
    data=csv,
    file_name='large_df.csv',
    mime='text/csv',
)
```

### Checkbox

```py
agree = st.checkbox('I agree')
if agree:
    st.write('Great!')
```

### Radio Button

```py
genre = st.radio(
    "What's your favorite movie genre",
    ('Comedy', 'Drama', 'Documentary'))
if genre == 'Comedy':
    st.write('You selected comedy.')
else:
    st.write("You didn't select comedy.")
```

### Select

```py
option = st.selectbox(
    'How would you like to be contacted?',
    ('Email', 'Home phone', 'Mobile phone'))
st.write('You selected:', option)
```

### Multiselect

```py
options = st.multiselect(
    'What are your favorite colors',
    ['Green', 'Yellow', 'Red', 'Blue'],
    ['Yellow', 'Red'])
st.write('You selected:', options)
```

### Slider

```py
values = st.slider(
    'Select a range of values',
    0.0, 100.0, (25.0, 75.0))
st.write('Values:', values)
```

### Range Select

```py
start_color, end_color = st.select_slider(
    'Select a range of color wavelength',
    options=['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'],
    value=('red', 'blue'))
st.write('You selected wavelengths between', start_color, 'and', end_color)
```

### Text

```py
title = st.text_input('Movie title', 'Life of Brian')
st.write('The current movie title is', title)
```

### Number

```py
number = st.number_input('Insert a number')
st.write('The current number is ', number)
```

### Text Area

```py
txt = st.text_area('Text to analyze', '''
    It was the best of times, it was the worst of times, it was
    the age of wisdom, it was the age of foolishness, it was
    the epoch of belief, it was the epoch of incredulity, it
    was the season of Light, it was the season of Darkness, it
    was the spring of hope, it was the winter of despair, (
    ''')
st.write('Sentiment:', run_sentiment_analysis(txt))
```

### Date

```py
d = st.date_input(
    "When's your birthday",
    datetime.date(2019, 7, 6))
st.write('Your birthday is:', d)
```

### Time

```py
t = st.time_input('Set an alarm for', datetime.time(8, 45))
st.write('Alarm is set for', t)
```

### File Upload

```py
uploaded_file = st.file_uploader("Choose a file")
if uploaded_file is not None:
    # To read file as bytes:
    bytes_data = uploaded_file.getvalue()
    st.write(bytes_data)
    # To convert to a string based IO:
    stringio = StringIO(uploaded_file.getvalue().decode("utf-8"))
    st.write(stringio)
    # To read file as string:
    string_data = stringio.read()
    st.write(string_data)
    # Can be used wherever a "file-like" object is accepted:
    dataframe = pd.read_csv(uploaded_file)
    st.write(dataframe)
```

### Add widget to sidebar

```py
import streamlit as st

add_selectbox = st.sidebar.selectbox(
    "How would you like to be contacted?",
    ("Email", "Home phone", "Mobile phone")
)
```

API Cheatsheet [here](https://share.streamlit.io/daniellewisdl/streamlit-cheat-sheet/app.py).

### Model Deployment Example

## CNN Models

```PY
import streamlit as st
import tensorflow as tf
from PIL import Image, ImageOps
import numpy as np

from tensorflow import keras

st.title("Cat-Dog Classification")

@st.cache(allow_output_mutation=True)
def teachable_machine_classification(img, weights_file):
    # Load the model
    model = keras.models.load_model(weights_file)

    size = (160, 160)
    image = ImageOps.fit(img, size)
    image = np.asarray(image)

    img_reshape = image[np.newaxis, ...]

    # run the inference
    predictions = model.predict(img_reshape)
    predictions = tf.nn.sigmoid(predictions)
    predictions = tf.where(predictions < 0.5, 0, 1)
    
    return  predictions

st.sidebar.header("Please input an image to be classified:")
uploaded_file = st.sidebar.file_uploader("Choose an Cat or Dog Image...", type="jpg")
    
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded file', use_column_width=True)
    st.write("")
    st.write("Classifying...")
    label = teachable_machine_classification(image, 'saved/modelImage')
    if label == 1:
        st.write("Its a Dog")
    else:
        st.write("Its a Cat")
```

## RNN Models

```py
import streamlit as st

from tensorflow import keras

st.title("SMS Spam Classification")

@st.cache(allow_output_mutation=True)
def teachable_machine_classification(text, weights_file):
    # Load the model
    model = keras.models.load_model(weights_file)


    # run the inference
    predictions = model.predict([text])
    predictions = predictions.argmax(axis=1)

    return  predictions

st.header("Please input sentences to be classified:")
userText = st.text_area('Input your sentences here')

if userText:
    st.write("")
    st.write("Classifying...")
    label = teachable_machine_classification(userText, 'saved/modelText')
    if label == 0:
        st.write("Its neutral")
    elif label == 1:
        st.write("Its a Spam")
    else:
        st.write("Its not a Spam")
```

## Heroku Deployment

### Create a requirements.txt, setup.sh, and Procfile.

requirements.txt:

```py
streamlit
tensorflow-cpu
Pillow
numpy
```

setup.sh:

```sh
mkdir -p ~/.streamlit/
echo "\
[server]\n\
headless = true\n\
port = $PORT\n\
enableCORS = false\n\
\n\
" > ~/.streamlit/config.toml
```

Procfile:

```procfile
web: sh setup.sh && streamlit run app.py
```
"""